### ISSUE TITLE
Add new Gulp task - Send emails to Litmus

### ISSUE THREAD

**Issue by m-bodmer** [matt-harris/outline-mail#2]
It would be awesome if we have a Gulp task that would send emails to Litmus once built to test cross-browser. There is already an NPM module we can use:

https://www.npmjs.com/package/gulp-litmus

**Comment by matt-harris** [comment]
Hey @m-bodmer great suggestion! I will try and get this added over the next couple of days. cheers!

**Comment by m-bodmer** [comment]
Awesome, if you'd like I can try adding it in as well.
